petition/urls.py
# -*- coding: utf-8 -*-
#
# petition/urls.py
#
# Copyright (C) 2011-16 Tomáš Pecina <tomas@pecina.cz>
#
# This file is part of petition.pecina.cz, a web-based petition
# application.
#
# This application is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This application is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.         
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from django.conf.urls import url, include
from django.contrib.auth.views import login, settings
from .views import petitionform, petitionlist, petitiondetail, petitiondel, \
                   signaturelist, slist, signaturedetail, signaturedel, \
                   export, doexport, pwchange, logout, view, redir, robots, cron

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

settings.LOGIN_URL = '/admin/login/'
settings.LOGOUT_URL = '/admin/logout/'

urlpatterns = [
    url(r'^admin/petitionform/((?P<id>\d+)/)?$',
        petitionform,
        name='petitionform'),
    url(r'^admin/petitionlist/$',
        petitionlist,
        name='petitionlist'),
    url(r'^admin/petitiondetail/(?P<id>\d+)/$',
        petitiondetail,
        name='petitiondetail'),
    url(r'^admin/petitiondel/(?P<id>\d+)/$',
        petitiondel,
        name='petitiondel'),
    url(r'^admin/signaturelist/(?P<id>\d+)/((?P<off>\d+)/)?$',
        signaturelist,
        name='signaturelist'),
    url(r'^list/$',
        slist,
        name='slist'),
    url(r'^admin/signaturedetail/(?P<id>\d+)/$',
        signaturedetail,
        name='signaturedetail'),
    url(r'^admin/signaturedel/$',
        signaturedel,
        name='signaturedel'),
    url(r'^admin/export/(?P<id>\d+)/$',
        export,
        name='export'),
    url(r'^admin/doexport/(?P<id>\d+)/$',
        doexport,
        name='doexport'),
    url(r'^admin/pwchange/$',
        pwchange,
        name='pwchange'),
    url(r'^admin/logout/$',
        logout,
        name='logout'),
    url(r'robots.txt$',
        robots),
    url(r'^admin/cron/$',
        cron),
    url(r'^admin/login/$',
        login,
        {'template_name': 'login.html'},
        name='login'),
    url(r'^admin/',
        include(admin.site.urls)),
    url(r'^((?P<name>[a-z][a-z0-9\-_]*)/)?$',
        view,
        name='view'),
    url(r'^(?P<par>.*\..*)$',
        redir,
        name='redir'),
]

petition/data/models.py
# -*- coding: utf-8 -*-
#
# petition/data/models.py
#
# Copyright (C) 2011-16 Tomáš Pecina <tomas@pecina.cz>
#
# This file is part of petition.pecina.cz, a web-based petition
# application.
#
# This application is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This application is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.         
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Petition(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=30, unique=True)
    domain = models.CharField(max_length=255, blank=True)
    email = models.EmailField(blank=True)
    closed = models.BooleanField()
    longname = models.CharField(max_length=255)
    keywords = models.CharField(max_length=255, blank=True)
    css = models.TextField(blank=True)
    text = models.TextField()
    counter = models.IntegerField()
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)

    def __str__(self):
        return self.longname

class Signature(models.Model):
    petition = models.ForeignKey(Petition)
    name = models.CharField(max_length=30, db_index=True)
    occupation = models.CharField(max_length=255, blank=True)
    occupation_hidden = models.BooleanField()
    address = models.CharField(max_length=255)
    address_hidden = models.BooleanField()
    birthdate = models.DateField(blank=True, null=True)
    birthdate_hidden = models.BooleanField()
    email = models.EmailField(blank=True)
    email_hidden = models.BooleanField()
    note = models.TextField(blank=True)
    note_hidden = models.BooleanField()
    ip = models.GenericIPAddressField()
    domain = models.CharField(max_length=255)
    reported = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)

    def __str__(self):
        return self.name

petition/views.py
# -*- coding: utf-8 -*-
#
# petition/views.py
#
# Copyright (C) 2011-16 Tomáš Pecina <tomas@pecina.cz>
#
# This file is part of petition.pecina.cz, a web-based petition
# application.
#
# This application is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This application is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.         
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from django.http import HttpResponse, HttpResponseRedirect, \
                        HttpResponsePermanentRedirect, Http404
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.core.mail import send_mail
from django.template import Context
from django.template.loader import get_template
from django.db import connection
from django.views.decorators.cache import never_cache
from django.contrib.auth.models import User
from re import match
from time import strftime, time, localtime
from datetime import datetime
from socket import gethostbyaddr
from bs4 import BeautifulSoup
from xml.sax.saxutils import escape
import reportlab.rl_config
from reportlab.pdfbase.pdfmetrics import registerFont, registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import Paragraph, SimpleDocTemplate, LongTable, \
                               TableStyle
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib.pagesizes import A4
from io import BytesIO
import os.path
from petition.forms import PetitionForm, SignatureForm
from petition.data.models import Petition, Signature

APP = 'petition'

VERSION = '1.0'

URL_BASE = 'petice.pecina.cz'
BATCH = 100

def cb2s(c):
    if c:
        return 'ano'
    else:
        return 'ne'

def oe(n):
    if n % 2:
        return 'odd'
    else:
        return 'even'

def norm(x, batch=BATCH):
    return (x // batch) * batch

def gennav(
        off,
        total,
        prefix,
        suffix='',
        batch=BATCH,
        i0='&lt;&lt;',
        i1='&lt;',
        i2='&gt;',
        i3='&gt;&gt;',
        a0='<a href="',
        a1='">',
        a2='</a>',
        g0='<span class="grayed">',
        g1='</span>',
        s0='',
        s1='&nbsp;&nbsp;',
        s2='&nbsp;&nbsp;<span class="pager">',
        s3='&nbsp;/&nbsp;',
        s4='</span>&nbsp;&nbsp;',
        s5='&nbsp;&nbsp;',
        s6=''):
    i = [i0, i1, i2, i3]
    n = [-1] * 4
    if off:
        n[0] = 0
        n[1] = off - batch
    if off + batch < total:
        n[2] = off + batch
        n[3] = norm(total - 1)
    p1 = (off // batch) + 1
    p2 = ((total - 1) // batch) + 1
    t = list(range(4))
    for j in range(4):
        if n[j] < 0:
            t[j] = g0 + i[j] + g1
        else:
            t[j] = a0 + prefix + str(n[j]) + suffix + a1 + i[j] + a2
    return s0 + t[0] + s1 + t[1] + s2 + str(p1) + s3 + str(p2) + \
        s4 + t[2] + s5 + t[3] + s6

def error(request):
    var = {'page_title': 'Interní chyba aplikace', 'suppress_topline': True}
    return render(request, 'error.html', var)

def unauth(request):
    var = {'page_title': 'Neoprávněný přístup'}
    return render(request, 'unauth.html', var)

def mainpage(request):
    return HttpResponseRedirect('/admin/petitionlist/')

def redir(request, par):
    return HttpResponsePermanentRedirect('http://www.pecina.cz/petice/' + par)

def newXML(data):
    xml = BeautifulSoup(data, 'lxml')
    xml.is_xml = True
    return xml

def xmldecorate(tag, table):
    if table.has_key(tag.name):
        for key, val in table[tag.name].items():
            tag[key] = val
    return tag

def xmlescape(t):
    return escape(t).strip()

def view(request, name=''):
    fields = ['longname', 'keywords', 'css', 'text', 'counter', 'closed']
    sfields = ['name', 'address', 'address_hidden', 'occupation',
               'occupation_hidden', 'birthdate', 'birthdate_hidden', 'email',
               'email_hidden', 'note', 'note_hidden']
    var = {'display_stat': True, 'display_thankyou': False, 'errors': False}
    if name:
        p = Petition.objects.filter(name=name)
    else:
        host = request.META.get('HTTP_HOST')
        if host == URL_BASE:
            return mainpage(request)
        p = Petition.objects.filter(domain=host)
    if not p:
        raise Http404()
    p = p[0]
    if not name:
        name = ''
    var['id'] = name
    var['page_title'] = p.longname
    var['total'] = p.signature_set.count()
    if request.method == 'GET':
        thankyou = request.GET.get('thankyou')
        if not thankyou:
            cursor = connection.cursor()
            cursor.execute(('update data_petition set counter=counter+1 ' \
                            'where id=%u' % p.id), [])
        for t in fields:
            var[t] = p.__getattribute__(t)
        closed = var['closed']
        var['display_form'] = (not (thankyou or closed))
        var['display_closed'] = closed
        var['display_thankyou'] = thankyou
    elif request.method == 'POST':
        if p.closed:
            return error(request)
        f = SignatureForm(request.POST)
        if f.is_valid():
            cd = f.cleaned_data
            cd['ip'] = request.META.get('REMOTE_ADDR').split(',')[0]
            try:
                cd['domain'] = gethostbyaddr(cd['ip'])[0]
            except:
                cd['domain'] = cd['ip']
            cd['petition_id'] = p.id
            s = Signature(**cd)
            if s.save():
                return error(request)
            else:
                return HttpResponseRedirect('/%s/?thankyou=1' % name)
        var['errors'] = True
        for t in fields:
            var[t] = p.__getattribute__(t)
        for t in sfields:
            var[t] = request.POST.get(t)
            if f[t].errors:
                var[t + '_error'] = 'err'
            else:
                var[t + '_error'] = 'ok'
        var['display_form'] = True
    else:
        return error(request)
    return render(request, 'petitionbody.html', var)

@login_required
def petitionform(request, id=0):
    u = request.user
    uid = u.id
    fields = ['name', 'domain', 'email', 'closed', 'longname', 'keywords',
              'css', 'text']
    var = {'url_base': URL_BASE, 'errors': False}
    if request.method == 'GET':
        if id:
            p = Petition.objects.filter(pk=id)
            if not p:
                return error(request)
            p = p[0]
            if p.user_id != uid and not u.is_superuser:
                return unauth(request)
            var.update({'id': id, 'page_title': 'Úprava petice'})
            for t in fields:
                var[t] = p.__getattribute__(t)
                var[t + '_error'] = 'ok'
        else:
            var.update({'id': 0, 'page_title': 'Nová petice'})
            for t in fields:
                var[t + '_error'] = 'ok'
    elif request.method == 'POST':
        if not id:
            id = 0
        f = PetitionForm(request.POST)
        if f.is_valid():
            cd = f.cleaned_data
            if cd['id']:
                p = Petition.objects.filter(pk=cd['id'])
                if not p:
                    return error(request)
                p = p[0]
                if p.user_id != uid and not u.is_superuser:
                    return unauth(request)
                cd['user'] = p.user
                cd['timestamp'] = p.timestamp
                cd['counter'] = p.counter
            else:
                del cd['id']
                cd['user'] = u
                cd['counter'] = 0
            p = Petition(**cd)
            if p.save():
                return error(request)
            else:
                return mainpage(request)
        else:
            var.update({'errors': True, 'id': id})
            if id:
                var['page_title'] = 'Úprava petice'
            else:
                var['page_title'] = 'Nová petice'
            for t in fields:
                var[t] = request.POST.get(t)
                if f[t].errors:
                    var[t + '_error'] = 'err'
                else:
                    var[t + '_error'] = 'ok'
    else:
        return error(request)
    return render(request, 'petitionform.html', var)

@login_required
def petitionlist(request):
    u = request.user
    uid = u.id
    fields = ['id', 'user', 'name', 'domain', 'longname']
    var = {'page_title': 'Přehled petic',
           'superuser': u.is_superuser,
           'rows': []}
    if u.is_superuser:
        p = Petition.objects.all().order_by('timestamp')
    else:
        p = Petition.objects.filter(user=uid).order_by('timestamp')
    n = 0
    for row in p:
        r = {}
        for t in fields:
            r[t] = row.__getattribute__(t)
        r['timestamp'] = row.timestamp.strftime('%d.%m.%Y')
        r['closed'] = cb2s(row.closed)
        n += 1
        r['number'] = n
        r['class'] = oe(n)
        r['total'] = row.signature_set.count()
        var['rows'].append(r)
    return render(request, 'petitionlist.html', var)

@login_required
def petitiondetail(request, id=0):
    u = request.user
    uid = u.id
    fields = ['id', 'name', 'domain', 'email', 'longname', 'keywords',
              'counter']
    var = {'url_base': URL_BASE, 'page_title': 'Podrobnosti o petici'}
    p = Petition.objects.filter(pk=id)
    if not p:
        return error(request)
    p = p[0]
    if p.user_id != uid and not u.is_superuser:
        return unauth(request)
    for t in fields:
        var[t] = p.__getattribute__(t)

petition/templates/admin.html
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- $Id: htmlquickstart.kmdr 768844 2008-01-30 19:21:23Z amantia $ -->
<head>
  <title>{% block pagetitle %}{{ page_title|default:"Přihlášení" }}{% endblock %}</title>
  <meta name="GENERATOR" content="Quanta Plus" />
  <meta name="AUTHOR" content="Tomáš Pecina" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Language" content="cs" />
  <style type="text/css">
  /* <![CDATA[ */
    body, h1, h2 { color: #000040; background-color: #e4ecff; font-family: Verdana, "DejaVu Sans", sans-serif; }
    body { margin: 0; font-size: 15px; }
    h1, h2 { text-align: center; }
    table { border-collapse: collapse; }
    td { padding: 1px 3px; }
    h1 { font-size: 21px; font-weight: bold; margin-top: 30px; }
    h2 { font-size: 17px; font-weight: normal; }
    table.big * { }
    tr.header, tr.footer, tr.topline { background-color: #c4e0ff; }
    div.warning { border-style: solid; border-width: 2px; padding: 4px 8px; text-align: center; margin-bottom: 12px; background-color: #c4e0ff; }
    a, span.pager { color: #2551b7; text-decoration: none; }
    tr.footer a, span.pager { }
    span.pager { font-weight: normal; }
    a:hover { color: #e00000; }
    .grayed { color: #f2f6ff; }
    tr.even { background-color: #f2f6ff; }
    tr.odd { background-color: #ffffff; }
    tr.even td, tr.odd td, th, tr.footer td { padding: 3px 13px; }
    td.hidden { color: #647480; }
    #detail td, #detail th { padding: 3px 10px; }
    .topline * { font-size: 12px; }
    .res { font-style: italic; text-align: center; font-size: 15px; margin-bottom: 15px; }
    p.foot { font-size: 11px; text-align: center; }
    fieldset, hr { border-color: #c0c0ff; }
    label.err, span.err { color: #e00000; }
    label.err { font-weight: bold; }
    input.err, textarea.err { background: #ffecec; }
    .ok { }
  /* ]]> */
  </style>
</head>
<body>
{% if page_title and not suppress_topline %}<table style="width: 100%;"><tr class="topline"><td align="right"><a href="/admin/pwchange/">změnit heslo</a> / <a href="/admin/logout/">odhlásit</a></td></tr></table>{% endif %}
<table style="width: 85%; margin: auto;">
  <tr><td>
{% block page_contents %}{% endblock %}
  </td></tr>
</table>
{% include 'notice.html' %}
</body>
</html>

petition/templates/error.html
{% extends "admin.html" %}

{% block page_contents %}
<h1 style="text-align: center;">{{ page_title }}</h1>
<p style="text-align: center;">Omlouváme se, ale došlo k interní chybě. Zkuste akci provést znovu, v případě přetrvávajících problémů se obraťte na <a href="mailto:Tomas Pecina &lt;tomas@pecina.cz&gt;?subject=Chyba v aplikaci Petice">autora aplikace</a>.</p>
{% endblock %}

petition/templates/formwarning.html
<div class="warning">Formulář obsahuje chyby. Opravte, prosím, <span class="err">červeně</span> označená pole.</div>

petition/templates/logout.html
{% extends "admin.html" %}

{% block page_contents %}
<h1 style="text-align: center;">{{ page_title }}</h1>
<p style="text-align: center;">Byli jste odhlášeni.</p>
{% endblock %}

petition/templates/petitiondel.html
{% extends "admin.html" %}

{% block page_contents %}
<h1 style="text-align: center;">{{ page_title }}</h1>
<p style="text-align: center;">Opravdu chcete smazat petici "{{ longname }}", která má {{ total }} podpisů?</p>
<form action="" method="post" enctype="multipart/form-data">
<p style="text-align: center;"><input type="submit" name="del" value="Ano" /> &nbsp; <input type="submit" name="del" value="Ne" /></p>
{% csrf_token %}
</form>
{% endblock %}

petition/templates/petitionform.html
{% extends "admin.html" %}

{% block page_contents %}
<form action="" method="post" enctype="multipart/form-data">
  <table style="margin: auto;">
    <tr><td></td><td><h1 style="text-align: left; margin-bottom: 8px; ">{{ page_title }}</h1></td></tr>
    {% if errors %}<tr><td></td><td class="warning">{% include "formwarning.html" %}</td></tr>{% endif %}
    <tr><td align="right"><label for="id_name" class="{{ name_error }}">Adresa:</label></td><td><span class="{{ name_error }}">http://{{ url_base }}/ </span><input type="text" name="name" value="{{ name }}" maxlength="30" id="id_name" class="{{ name_error }}" /><span class="{{ name_error }}"> (pouze znaky 'a'&ndash;'z', '0'&ndash;'9', '-' a '_')</span></td></tr>
    <tr><td align="right"><label for="id_domain" class="{{ domain_error }}">Vlastní doména:</label></td><td><span class="{{ domain_error }}">http:// </span><input type="text" name="domain" value="{{ domain }}" maxlength="255" id="id_domain" class="{{ domain_error }}" /><span class="{{ domain_error }}"> (musí být nastavena v DNS)</span></td></tr>
    <tr><td align="right"><label for="id_email" class="{{ email_error }}">E-mail pro pravidelné zprávy:</label></td><td><input type="text" name="email" value="{{ email }}" maxlength="75" id="id_email" class="{{ email_error }}" /><span class="{{ email_error }}"> (nepovinný)</span></td></tr>
    <tr><td align="right"><label for="id_closed" class="{{ closed_error }}">Petice ukončena:</label></td><td><input type="checkbox" name="closed"{% if closed %} checked{% endif %} id="id_closed" class="{{ closed_error }}" /></td></tr>
    <tr><td align="right"><label for="id_longname" class="{{ longname_error }}">Název petice:</label></td><td><input type="text" name="longname" value="{{ longname }}" maxlength="255" id="id_longname" class="{{ longname_error }}" style="width: 100%;" /></td></tr>
    <tr><td align="right"><label for="id_keywords" class="{{ keywords_error }}">Klíčová slova:</label></td><td><input type="text" name="keywords" value="{{ keywords }}" maxlength="255" id="id_keywords" class="{{ keywords_error }}" style="width: 100%;" /></td></tr>
    <tr><td align="right" valign="top"><label for="id_css" class="{{ css_error }}">Styly (CSS):</label></td><td><textarea name="css" rows="8" cols="" id="id_css" class="{{ css_error }}" style="width: 100%;">{{ css }}</textarea></td></tr>
    <tr><td align="right" valign="top"><label for="id_text" class="{{ text_error }}">Text petice (HTML):</label></td><td><textarea name="text" rows="25" cols="" id="id_text" class="{{ text_error }}" style="width: 100%;">{{ text }}</textarea></td></tr>
    <tr><td align="right"></td><td><input type="submit" name="submit" value="Odeslat" /><input type="hidden" name="id" value="{{ id }}" /></td></tr>
  </table>
  {% csrf_token %}
</form>
{% endblock %}

petition/templates/signatureform.html
<form action="" method="post" enctype="multipart/form-data" onsubmit="fn=document.getElementById('id_name'); if (fn.value=='') { alert('Zadejte, prosím, své jméno a příjmení'); fn.focus(); return false; } fa=document.getElementById('id_address'); if (fa.value=='') { alert('Zadejte, prosím, adresu svého bydliště'); fa.focus(); return false; } if ((fn.value + fa.value + document.getElementById('id_occupation').value + document.getElementById('id_note').value).search('http://') >= 0) { alert('Odkazy nejsou povoleny'); return false; } return true;">
<fieldset><legend>Připojuji svůj podpis pod text petice</legend>
<table style="margin: auto;">
    {% if errors %}<tr><td colspan="3" class="warning">{% include "formwarning.html" %}</td></tr>{% endif %}
    <tr><td class="c1" style="padding-top: 6px;"><label for="id_name" class="{{ name_error }}">Jméno&nbsp;a&nbsp;příjmení:</label></td><td style="width: 250px; padding-top: 6px;"><input type="text" name="name" maxlength="30" value="{{ name }}" id="id_name" class="{{ name_error }}" /></td><td></td></tr>
    <tr><td class="c1"><label for="id_address" class="{{ address_error }}">Adresa:</label></td><td><input type="text" name="address" maxlength="255" value="{{ address }}" id="id_address" class="{{ address_error }}" /></td><td class="c3"><input type="checkbox" name="address_hidden"{% if address_hidden %} checked{% endif %} id="id_address_hidden" /></td></tr>
    <tr><td></td><td style="padding-top: 1px; padding-bottom: 3px; text-align: center;">Nepovinné údaje:</td><td></td></tr>
    <tr><td class="c1"><label for="id_occupation" class="{{ occupation_error }}">Povolání:</label></td><td><input type="text" name="occupation" maxlength="255" value="{{ occupation }}" id="id_occupation" class="{{ occupation_error }}" /></td><td class="c3"><input type="checkbox" name="occupation_hidden"{% if occupation_hidden %} checked{% endif %} id="id_occupation_hidden" /></td></tr>
    <tr><td class="c1"><label for="id_birthdate" class="{{ birthdate_error }}">Datum&nbsp;narození:</label></td><td><input type="text" name="birthdate" value="{{ birthdate }}" maxlength="12" id="id_birthdate" class="{{ birthdate_error }}" /></td><td class="c3"><input type="checkbox" name="birthdate_hidden"{% if birthdate_hidden %} checked{% endif %} id="id_birthdate_hidden" /></td></tr>
    <tr><td class="c1"><label for="id_email" class="{{ email_error }}">E-mail:</label></td><td><input type="text" name="email" maxlength="75" value="{{ email }}" id="id_email" class="{{ email_error }}" /></td><td class="c3"><input type="checkbox" name="email_hidden"{% if email_hidden %} checked{% endif %} id="id_email_hidden" /></td></tr>
    <tr><td class="c1" valign="top"><label for="id_note" class="{{ note_error }}">Poznámka:</label></td><td><textarea name="note" rows="5" cols="" id="id_note" class="{{ note_error }}" style="width: 100%;">{{ note }}</textarea></td><td class="c3"><input type="checkbox" name="note_hidden"{% if note_hidden %} checked{% endif %} id="id_note_hidden" /></td></tr>
    <tr><td></td><td style="text-align: center;"><input type="submit" name="submit" value="Podepsat" style="width: auto;" /></td><td></td></tr>
</table></fieldset>
<fieldset id="notes"><legend>Poznámky k formuláři</legend>
<p>Internetová petice sice není peticí ve smyslu <a href="http://www.senat.cz/cinnost/petice/zakon_peticni.php">zákona č. 85/1990 Sb.</a> o právu petičním, avšak je jí po praktické stránce zcela rovnocenná. Jméno a adresa jsou povinné, ostatní údaje zadávat nemusíte. Čím víc údajů o sobě vyplníte, tím důvěryhodnější váš podpis pod peticí bude.</p>
<p>Adresáti petice obdrží všechny zadané údaje, ale v&nbsp;seznamu signatářů budou uvedeny jen ty, které zvolíte. Jméno a příjmení se zobrazují vždy, u ostatních informací můžete sami určit, zda mají být zveřejněny. Zaškrtnete-li políčko napravo od zadávacího pole, příslušný údaj zůstane v&nbsp;seznamu skryt.</p>
<p>Pole <i>Poznámka</i> je určeno pro vaše vlastní vyjádření, sdělení autorům nebo pro komentáře k&nbsp;petici.</p>
<p>Odesláním elektronického formuláře vyslovujete souhlas se zpracováním zadaných osobní údajů, včetně citlivých, ve smyslu <a href="http://www.uoou.cz/uoou.aspx?menu=4&amp;submenu=5&amp;loc=20">zákona č. 101/2000 Sb.</a> o ochraně osobních údajů, ve znění pozdějších předpisů, pro účely a v&nbsp;rozsahu této petiční akce.</p>
</fieldset>{% csrf_token %}</form>

petition/templates/thankyou.html
<fieldset>
<p style="text-align: center; font-weight: bold; font-size: 18px;">Děkujeme za váš podpis!</p>
</fieldset>

petition/templates/unauth.html
{% extends "admin.html" %}

{% block page_contents %}
<h1 style="text-align: center;">{{ page_title }}</h1>
<p style="text-align: center;">Nemáte přístup k této operaci. Pravděpodobně se pokoušíte pracovat s peticí, jejímž nejste vlastníkem, nebo jinak obejít bezpečnostní systém aplikace.</p>
<p style="text-align: center;">Domníváte-li se, že tomu tak není, obraťte se na <a href="mailto:Tomas Pecina &lt;tomas@pecina.cz&gt;?subject=Chyba v aplikaci Petice">autora aplikace</a>.</p>
{% endblock %}